user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: userBundle:Default:index }
_homepage:
    pattern:  /user/add
    defaults: { _controller: userBundle:User:add }

pointer:
    pattern:  /user/pointer
    defaults: { _controller: userBundle:Default:pointer }
